# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       데이터 과학 블로그
email:       ''
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://leadgoon.github.io/' # The base hostname & protocol for your site
twitter:     'https://twitter.com/'
github:      'https://github.com/'
instagram:   'https://www.instagram.com/'
facebook:    'https://www.facebook.com/'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
